modLoader = "javafml"
loaderVersion = "${loader_version_range}"
issueTrackerURL = "https://github.com/whimsicalwren/crows-nest/issues"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://github.com/whimsicalwren/crows-nest"
authors = "wren"
description = '''A clientside mod that adds some useful utilities for Sable!'''
logoFile = "icon.png"

[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="sable"
mandatory=true
versionRange="[${sable_version},)"
ordering="AFTER"
side="BOTH"